#### **FastText**

- Word2Vec에서 OOV(Out of Voca) 문제를 해결하기 위한 모델
- Word2Vec은 '강아지'와 '강아지들' 두 단어를 다른 단어로 생각
- FastText는 기존의 Word2Vec 학습 방식은 동일하지만 기준이 되는 문자가 다름
    - Word2Vec은 단어를 기준, FastText는 글자를 기준
    - '강아지' → '강', '아', '지', '강아', '아지', '강아지' (n-gram의 방식)
    - subword를 기준으로 문자들을 벡터화
    - Word2Vec 매개변수들을 이용하지만 추가적으로 subword 관련한 매개변수들을 사용
        - 최소 길이의 subword → `min_n` (default 3)
        - 최대 길이의 subword → `max_n` (default 6)
        - `min_n` = 0, `max_n` = 0 으로 설정하면 subword 사용 금지 → Word2Vec 방식 이용
        - `min_n`이 `max_n`보다 작거나 같게 설정
        - `bucket` 매개변수는 단어(subword) 사전의 개수를 제한 (메모리 과부하 방지)

In [2]:
from gensim.models import Word2Vec, FastText

In [3]:
sentences = [
    ['이커머스', '데이터', '분석', '진행'],
    ['상품', '리뷰', '감성', '분석', '합니다'],
    ['형태소', '단위', '임베딩', '가능']
]

In [4]:
model_wv = Word2Vec(
    sentences = sentences,
    window = 3,
    vector_size = 50,
    min_count = 1,
    sg = 1,
    epochs = 10
)

In [5]:
model_ft = FastText(
    sentences = sentences,
    window = 3,
    vector_size = 50,
    min_count = 1,
    sg = 1,
    epochs = 50,
    min_n = 2,
    max_n = 4
)

In [6]:
# 특정 단어의 단위 벡터 출력

model_wv.wv['이커머스']

array([ 0.0054888 , -0.0167182 ,  0.01571161,  0.01707221, -0.01916817,
        0.00489253,  0.01980994, -0.01533161, -0.01393384, -0.01547303,
        0.01679185, -0.00136267,  0.01828882, -0.01631644,  0.00748617,
        0.00527009,  0.00148543,  0.00465535, -0.01493819, -0.01871675,
        0.00470915,  0.01229691,  0.01597138,  0.01147179, -0.00155467,
        0.01661233, -0.01867263,  0.00681227,  0.00053351,  0.00771449,
        0.01477157, -0.01345033,  0.01116896, -0.01904445, -0.00160892,
       -0.01737747, -0.01019735,  0.01857845, -0.00371652,  0.00582885,
        0.01814256,  0.01787627, -0.01641687, -0.00602463,  0.01977321,
        0.01020886, -0.00317617, -0.01738404,  0.00592303, -0.0133518 ],
      dtype=float32)

In [7]:
model_ft.wv['이커머스']

array([ 0.00161844, -0.00056444,  0.00173306,  0.00058625,  0.0022801 ,
       -0.00345662, -0.0025083 , -0.00061036,  0.00105468, -0.00114948,
       -0.0048836 , -0.00141463,  0.00162329, -0.00409175, -0.00358844,
        0.00067483, -0.00421666,  0.00461058, -0.00176603, -0.00178279,
       -0.00093679,  0.00316449, -0.00432388,  0.00661264, -0.00446917,
        0.00400047, -0.00105416, -0.00369074, -0.00305697, -0.00117151,
        0.00037995, -0.0050687 ,  0.00180202, -0.00104049, -0.00366212,
       -0.00555263, -0.00220856,  0.00587034,  0.00026911,  0.00263595,
        0.00616197, -0.00195178, -0.00015047, -0.0048273 ,  0.00194105,
       -0.00037642, -0.00171464, -0.00555996,  0.00119484,  0.00359364],
      dtype=float32)

In [8]:
# 단어 간의 유사도
model_wv.wv.most_similar('데이터', topn = 3)

[('상품', 0.23735211789608002),
 ('감성', 0.16942839324474335),
 ('임베딩', 0.12119603902101517)]

In [9]:
model_ft.wv.most_similar('데이터', topn = 3)

[('이커머스', 0.28148913383483887),
 ('리뷰', 0.22393549978733063),
 ('감성', 0.11484096199274063)]

In [12]:
# 단어 사전에 없는 단어를 이용해서 단위 벡터를 생성?
# Word2Vec은 단어 사전에 없는 단어로 단위 벡터화 불가능
# model_wv.wv['감정']

# FastText는 새로운 단어에 대한 단위 벡터 생성 가능
model_ft.wv['감정']

array([-5.5013583e-03, -2.2979849e-03, -2.5734769e-03,  4.0556141e-03,
        5.9932917e-03,  7.8135323e-05, -3.3466425e-04,  1.2378028e-03,
       -5.6759850e-03, -1.9016862e-03,  5.5369554e-04, -4.3604099e-03,
        1.8574778e-03, -1.6514865e-03,  1.2156385e-03,  4.9276948e-03,
       -1.0717399e-03,  1.6748225e-03, -7.5539891e-03,  9.4375463e-04,
       -3.0825816e-03, -4.9547777e-03,  6.7924923e-04,  2.4481777e-03,
        1.9796055e-03, -2.2294174e-03, -3.4779435e-04,  4.1542869e-04,
        7.0489547e-03,  1.9074162e-03, -4.7414028e-03,  1.0020558e-02,
        5.4194313e-03,  6.6841054e-03, -7.0031253e-03,  3.0840908e-03,
        4.4810823e-03,  1.0817877e-02,  4.6283850e-03,  2.7074963e-03,
       -4.2120563e-03, -4.7758422e-03,  2.4732177e-03, -2.6553075e-03,
        9.1215409e-03, -2.9051458e-04,  4.3202689e-04, -6.9787470e-03,
        4.6269768e-03,  2.2767927e-03], dtype=float32)

In [ ]:
# 단어에 없는 단어로 유사한 단어를 찾을 수 있을까?

# model_wv.wv.most_similar('감정', topn = 3)
model_ft.wv.most_similar('감정', topn = 3)

[('가능', 0.18853062391281128),
 ('형태소', 0.18536968529224396),
 ('감성', 0.17655622959136963)]

In [17]:
sentences2 = [
    ['고양이', '고양이들', '귀엽다', '동물', '반려동물'],
    ['강아지', '강아지들', '귀엽다', '동물', '반려동물'],
    ['달리다', '달리는', '달림', '걷다', '걷는'],
    ['예쁘다', '예쁨', '예쁜', '매력적이다'],
    ['컴퓨터', '컴퓨팅', '컴퓨터들', '기계']
]

In [18]:
w2v = Word2Vec(
    sentences = sentences2,
    window = 3,
    min_count = 1,
    sg = 1,
    seed = 42
)

ft = FastText(
    sentences = sentences2,
    window = 3,
    min_count = 1,
    sg = 1,
    seed = 42,
    min_n = 2
)

In [19]:
# 단어 간의 유사도 확인
print(
    'Word2Vec 단어 간의 유사도:', w2v.wv.similarity('강아지', '강아지들')
)

print(
    'FastText 단어 간의 유사도:', ft.wv.similarity('강아지', '강아지들')
)

Word2Vec 단어 간의 유사도: 0.06403736
FastText 단어 간의 유사도: 0.4059004


In [21]:
# 비교 대상 단어들
test_text = [
    ['강아지', '강아지들'],
    ['고양이', '고양이들'],
    ['달리다', '달리는'],
    ['예쁘다', '예쁜'],
    ['컴퓨터', '컴퓨팅'],
    ['달리다', '걷다']
]

In [29]:
for word1, word2 in test_text:
    w2v_sim = w2v.wv.similarity(word1, word2)
    ft_sim = ft.wv.similarity(word1, word2)
    print(f'[{word1}] 와(과) [{word2}] 간의 유사도 - Word2Vec: {w2v_sim} | FastText: {ft_sim}')

[강아지] 와(과) [강아지들] 간의 유사도 - Word2Vec: 0.06403736025094986 | FastText: 0.40590038895606995
[고양이] 와(과) [고양이들] 간의 유사도 - Word2Vec: -0.07337046414613724 | FastText: 0.46013206243515015
[달리다] 와(과) [달리는] 간의 유사도 - Word2Vec: 0.04628410190343857 | FastText: 0.3028862476348877
[예쁘다] 와(과) [예쁜] 간의 유사도 - Word2Vec: 0.1387229710817337 | FastText: 0.06622864305973053
[컴퓨터] 와(과) [컴퓨팅] 간의 유사도 - Word2Vec: -0.05135166645050049 | FastText: 0.36511483788490295
[달리다] 와(과) [걷다] 간의 유사도 - Word2Vec: -0.06980345398187637 | FastText: -0.019979460164904594


In [30]:
# 상품명을 기준으로 특정 상품을 검색 시 연관된 상품의 목록을 확인
products = {
    'P001': '무선 이어폰 블루투스 노이즈캔슬링 충전케이스',
    'P002': '유선 이어폰 하이파이 금도금 플러그',
    'P003': '게이밍 마우스 RGB 경량 디자인',
    'P004': '무선 마우스 초경량 블루투스 듀얼모드',
    'P005': '헤드폰 노이즈캔슬링 유선'
}

In [35]:
# dict 형태 데이터에서 FastText에서 필요한 데이터는 values
data = products.values()

In [36]:
from konlpy.tag import Komoran

In [37]:
komoran = Komoran()

tokens_komoran = []
tokens_split = []

for name in data:
    tokens_komoran.append(komoran.morphs(name))
    tokens_split.append(name.split())

In [38]:
print(tokens_komoran)
print(tokens_split)

[['무선', '이어폰', '블루투스', '노이즈캔슬링', '충전', '케이스'], ['유선', '이어폰', '하이파', '이', '금도금', '플러그'], ['게이밍', '마우스', 'RGB', '경량', '디자인'], ['무선', '마우스', '초', '경량', '블루투스', '듀얼모드'], ['헤드폰', '노이즈캔슬링', '유선']]
[['무선', '이어폰', '블루투스', '노이즈캔슬링', '충전케이스'], ['유선', '이어폰', '하이파이', '금도금', '플러그'], ['게이밍', '마우스', 'RGB', '경량', '디자인'], ['무선', '마우스', '초경량', '블루투스', '듀얼모드'], ['헤드폰', '노이즈캔슬링', '유선']]


In [39]:
ft2 = FastText(
    sentences = tokens_split,
    window = 3,
    min_count = 1,
    sg = 1,
    min_n = 2,
    max_n = 4,
    seed = 42
)

In [40]:
# 상품명들을 벡터화
# 단어들의 단위 벡터를 구하고 → 평균을 내고 → L2 정규화를 이용하여 거리를 1로 변경

import numpy as np

In [44]:
def sent_vector(token, type = None):
    # token = 토큰화된 문장 데이터
    # type = None인 경우는 평균값, 'l2'인 경우는 L2 정규화
    vectors = []
    for word in token:
        vectors.append(ft2.wv[word])
    
    # vectors가 존재하지 않는 경우 (공백, 텍스트가 사라진 경우)
    if not vectors:
        return np.zeros(ft2.vector_size)
    
    # 단위 벡터들의 평균값을 구한다.
    v = np.mean(vectors, axis = 0)

    # type이 'l2'라면
    if type == 'l2':
        # 벡터의 거리로 나눠준다.
        # 벡터의 거리는? → numpy 거리 함수: linalg()
        v = v / (np.linalg.norm(v) + 1e-12)
    
    return v

In [45]:
# token_split을 이용하여 벡터화
items_vector = []
for token in tokens_split:
    items_vector.append(
        sent_vector(token)
    )

In [46]:
items_vector_l2 = []
for token in tokens_split:
    items_vector_l2.append(
        sent_vector(token, type = 'l2')
    )

In [48]:
from sklearn.metrics.pairwise import cosine_similarity

In [49]:
idx = list(products.keys()).index('P003')
idx

2

In [50]:
items_vector[2]

array([-3.2000005e-04,  3.1375766e-04,  5.1792839e-04,  6.5062125e-04,
        3.2906764e-04, -3.2266864e-04, -7.2865208e-05,  1.1439081e-03,
       -6.2371802e-04, -9.9430548e-04, -8.7191304e-04,  2.1039611e-03,
       -7.6008943e-04,  1.0854375e-03, -5.6152639e-04,  1.5596985e-03,
        5.0813780e-04,  9.3676476e-04,  5.4180349e-04, -4.0181767e-04,
       -7.1609503e-04, -1.4897682e-03,  1.8826611e-03, -3.2994780e-04,
        1.4246625e-03,  1.4619015e-03, -7.8024791e-04,  1.9024182e-04,
       -2.1541383e-04,  5.7493908e-05, -1.2820836e-03, -3.3797024e-04,
       -8.7603286e-04,  5.6498207e-04, -6.1838204e-05, -1.4575676e-03,
        1.5858545e-03,  2.5526801e-04,  6.1065855e-04,  1.0380448e-03,
       -9.7055730e-05,  1.1544621e-03,  8.2218682e-04,  1.2229892e-03,
       -8.6156128e-04,  1.6548103e-03,  7.3871185e-04,  7.2006613e-04,
       -4.3547711e-06, -2.4511060e-04, -9.4917062e-04,  1.7177424e-04,
       -1.0805454e-03,  5.1202701e-04, -3.5843122e-04,  9.0679585e-04,
      

In [51]:
cosine_similarity([items_vector[idx]], items_vector)

array([[0.01113469, 0.02338488, 1.        , 0.15756822, 0.1412824 ]],
      dtype=float32)

In [52]:
cosine_similarity([ft2.wv['마우스']], items_vector)

array([[0.18812653, 0.07292487, 0.49822837, 0.49449968, 0.29506552]],
      dtype=float32)

In [57]:
# 코사인 유사도를 이용해서 가장 근접한 상품의 이름을 출력하는 함수

def recommand_by_text(product_id):
    # dict.keys() 특정 id의 위치를 확인
    idx = list(products.keys()).index(product_id)

    # 해당 id 위치의 단위 벡터 데이터와 다른 상품들의 단위 벡터 데이터를 코사인 유사도를 이용하여 계산
    sims = cosine_similarity([items_vector[idx]], items_vector).ravel()
    
    # 내림차순 정렬
    order = sims.argsort()[::-1]

    # 추천 상품명을 담기 위한 빈 리스트 생성
    result = []
    for i in order:
        # 코사인 유사도가 1인 경우는 자기 자신일 때
        # list(products.keys())[i]의 값이 product_id와 같지 않은 경우를 보아야 함
        if list(products.keys())[i] != product_id:
        # 또는 if sims[i] != 1.0:
            result.append(
                [
                    list(products.values())[i], round(sims[i], 4)
                ]
            )
    return result

In [58]:
recommand_by_text('P001')

[['무선 마우스 초경량 블루투스 듀얼모드', np.float32(0.4768)],
 ['유선 이어폰 하이파이 금도금 플러그', np.float32(0.317)],
 ['헤드폰 노이즈캔슬링 유선', np.float32(0.2432)],
 ['게이밍 마우스 RGB 경량 디자인', np.float32(0.0111)]]

#### 문제
- 특정한 검색어를 입력했을 때 유사한 상품 목록 3개를 추천하는 함수를 생성
- `items_vector_l2` l2 정규화된 문장 벡터를 이용하여 코사인 유사도를 구하고 상위 3개의 추천 상품명을 출력

처참하게 망한 내 풀이^-^

In [ ]:
def recommand_head3(search_text):
    result1 = []
    for idx in range(len(tokens_split)):
        if search_text in tokens_split[idx]:
            result1.append(idx)
    sims = cosine_similarity([items_vector_l2[idx]], items_vector_l2).ravel()
    order = sims.argsort()[::-1]

    # 추천 상품명을 담기 위한 빈 리스트 생성
    result = []
    a = 1
    for i in order:
        if sims[i] != 1.0:
            result.append(
                [
                    list(products.values())[i], round(sims[i], 4)
                ]
            )
            a += 1
            if a == 3:
                break
    return result

In [110]:
recommand_head3('노이즈캔슬링')

[0.24324277 0.4691398  0.14128238 0.14518766 1.        ]


[['유선 이어폰 하이파이 금도금 플러그', np.float32(0.4691)],
 ['무선 이어폰 블루투스 노이즈캔슬링 충전케이스', np.float32(0.2432)]]

강사님 풀이

In [126]:
def recommand_by_search(text):
    # 검색어를 이용하여 등록된 상품 목록에서 유사한 상품을 추천
    # text를 이용해서 단위 벡터를 생성
    vector = ft2.wv[text]
    v = vector / (np.linalg.norm(vector) + 1e-12)

    sims = cosine_similarity( [v], items_vector_l2 ).ravel()
    order = sims.argsort()[::-1]

    result = []
    for i in order[:3]:
        result.append(
            [
                list(products.values())[i],
                round(sims[i], 4)
            ]
        )
    
    return result

In [127]:
recommand_by_search('노이즈캔슬링')

[['헤드폰 노이즈캔슬링 유선', np.float32(0.4451)],
 ['무선 이어폰 블루투스 노이즈캔슬링 충전케이스', np.float32(0.3391)],
 ['무선 마우스 초경량 블루투스 듀얼모드', np.float32(0.0278)]]